### ISSUE TITLE
Grey screen when force quitting from settings screen  on iOS

### ISSUE THREAD

**Issue by jrabensc** [casimir/frigoligo#125]
Steps to reproduce:

1. Go to settings screen
2. Force quit 
3. Open app again, screen is grey

Device: iPhone 15
iOS: 17.2.1
App version: 0.7.0+171

**Comment by casimir** [comment]
Thanks for the report. It's most likely due to an initialisation problem in the settings screen.

It only occurs in release mode and on a real device so nothing reaches the log. As you now I don't know how to debug it properly...

**Comment by casimir** [comment]
Just a note to myself, the settings Provider has been migrated to `riverpod` with #131. Updating `SettingsPage` to use the `riverpod` API will most likely fix this bug.

**Comment by casimir** [comment]
@jrabensc the fix has been shipped in https://github.com/casimir/frigoligo/releases/tag/v0.8.1
