### ISSUE TITLE
can't add new articles

### ISSUE THREAD

**Issue by e075e** [casimir/frigoligo#194]
# details

## from the app
It seems there's no way to add an article from the app itself, like a + button or "add url" from the top left menu

## from sharing function
1. Open the broswer (firefox, brave, etc)
2. Visit any page you like
3. Share it with frigoligo

# actual behaviour
Now frigoligo opens but nothing is added to the articles list

# expected behaviour
The article is added to wallabag
# device info
eOS (android 13)
Samsnung a52q

**Comment by casimir** [comment]
The feature to add an article from inside the app is currently worked on and will be available in the next version. See #198.

I can reproduce the issue with the sharing function, this is a bug. I'll work on a fix as soon as possible.

**Comment by casimir** [comment]
The 2 issues are addressed by #198 and #200 that will by shipped in the next release. Hopefully in a few days.

**Comment by casimir** [comment]
Released in https://github.com/casimir/frigoligo/releases/tag/v1.1.0
