### ISSUE TITLE
Translate Archive.today URLs to original URL

### ISSUE THREAD

**Issue by c4tb3rt** [casimir/frigoligo#197]
Sadly, articles disappear or are not fully readable by everyone or original articles have bene deleted. Reasons why people use archive.is or archive.ph to scrape an article for future reference.
_we know_, that is only half the work. You also need to find it back among the heaps of articles you have saved somewhere. Enter Wallabag.

What if you could save an archive.is/archive.ph-URL to Wallabag and it would save the archive-Url or - if still available - the original link (that can be found on the archive.is/.ph site?

For the basic functionality to add an article via a + in the app of via the sharing function from any other app,[ I refer to this Issue 14](https://github.com/casimir/frigoligo/issues/14) 

## From the app or via the sharing function in any other app

1. An archive.is/archive.ph URL is entered to be added to Wallabag. 
2. Frigoligo saves the article from the Archive.id/.ph page. 
3. Frigoligo assesses the Archive.is/.ph page ad follows the 'Saved from'-URL on that page. 
5. If the URL does not provide a 404, it saves that URL. If it does, it saves the Archive.is/.ph URL. 

# Actual behaviour

The original URL is saved to Wallabag (if [Issue 14](https://github.com/casimir/frigoligo/issues/14) is fixed).

# Expected Behaviour 

The article is saved with either the original URL or - if that provides a 404 - the Archive.today-URL
# Device Info

Not relevant, but Google Pixel 6A
Lineage OS 21 (Android 14)

**Comment by casimir** [comment]
I'm not sure I understand your request. The concept of wallabag is to archive web pages, keeping a copy in database.

Are you thinking about allowing an alternative archive source?
