### ISSUE TITLE
open link inside an article

### ISSUE THREAD

**Issue by AnthillSudoku** [casimir/frigoligo#217]
Touching a link inside an article does nothing.

Ideally it should shows a dialog that let you check the url and open it. For instance, [FairEmail](https://github.com/M66B/FairEmail) does this:

![Imagepipe_0](https://github.com/casimir/frigoligo/assets/15078341/aa77459b-719a-4abd-9a4b-5f632cb9331c)

**Comment by casimir** [comment]
Thanks for the report. This is a regression from recent changes, the fix will be available in the next release.
