### ISSUE TITLE
search articles using title

### ISSUE THREAD

**Issue by AnthillSudoku** [casimir/frigoligo#242]
It's not possible to search articles titles by a specific word. So, when you have lot's of articles, finding what you are looking for is tricky.

This can be implemented alongside #13 

# INTERFACE
A search button with the image of a lens could be added at the top bar, or at the botton right corner to make it easily reachable.

After pressing it, a popup appears and ask what to search and where:

| search field |
| where? |
| - title |
| - text |
| - all |

**Comment by casimir** [comment]
Fixed in #252. Starting version 2.0.0 you can change the behaviour of the text search using the button on the right of the search bar.
