### ISSUE TITLE
unable connect to server

### ISSUE THREAD

**Issue by gabrielparca** [casimir/frigoligo#251]
>Samsung A34 5G 
(SM-A346E/DSN)
>Android v14
>One UI v6.1
>Frigoligo v1.2.0 (2035)

Hi, get “Invalid API response” when trying to get the app to connect to the nextcloud server.

I have tried both 'https://kim.nl.tab.digital' (the actual url of my server) and the short iteration 'kim.nl.tab.digital' to the same result seen below: 

![Screenshot_20240904_104210.png](https://github.com/user-attachments/assets/48d542d2-1728-49e6-999e-a2a94aa2eb7d)

**Comment by casimir** [comment]
Are you sure about the address? I does not look like a wallabag server.
