### ISSUE TITLE
Issue with title being cut off

### ISSUE THREAD

**Issue by RayBB** [casimir/frigoligo#286]
Hey there,

First I wanted to say thank you so much for making this app. It is fantastic. As I've tried Wallabag many times and always felt frustrated with the UX despite it being great at extraction. I was even considering making a PWA for myself that's very simple to try to just have good offline reading on the plane. Your app should definitely go in the official wallabag docs when you feel comfortable because it's a great alternative so far!

Anyway, here's a small bug I'm getting on my Android 14 Pixel 7.

On some, just some, articles the title in the article (not the title bar) is cut off. In the screenshot it's scrolled all the way to the top already.

Just a small thing but might be an easy fix.

Example:
https://thecitypaperbogota.com/news/casa-de-monedas-latest-exhibition-redefines-colombias-changing-image/
![image](https://github.com/user-attachments/assets/a856da24-516c-4cec-b46e-5affc42052a7)

**Comment by casimir** [comment]
Thanks for the praises. My story is pretty similar, this app was just a "let's speed hack an offline wallabag this weekend" at the start.
I just found out that the app is actually listed in wallabag's wiki: https://github.com/wallabag/wallabag/wiki/wallabag-ecosystem#unofficial-clients

About your issue, a fix has just landed.
