### ISSUE TITLE
Crash logs on iPad

### ISSUE THREAD

**Issue by RayBB** [casimir/frigoligo#288]
I've experienced a few seemingly random crashes on the iPad version today (first day trying it on iPad).
Sometimes it crashes when I haven't even touched it for a minute but it's just open sitting there while I'm doing something on my phone.

I figured I'd share the logs of the two crashes here.
Also here's the article that has that 404 image that might be a problem.
https://www.labornotes.org/2008/08/are-industrial-unions-better-craft-not-always

Images redact my wallabag server.
![signal-2024-12-01-094126_002(1)](https://github.com/user-attachments/assets/bc87da2e-dd01-4b8c-8b47-c6bfdc17e9f7)
![signal-2024-12-01-092901_002(1)](https://github.com/user-attachments/assets/f591b754-43db-4e52-99ca-8614e03d598e)

**Comment by casimir** [comment]
The only culprit I can see is this line:
```
main: uncaught error (Null check operator used on a null value)
```
Sadly this is not much to work with. Do you still encounter the crashes and if so what is that last action you performed?

**Comment by RayBB** [comment]
I've been trying to reproduce the issue but it doesn't seem to be coming up anymore. So let's close this for now
