### ISSUE TITLE
Scrolling indicator shows 100% when you first open an article with no reading progress

### ISSUE THREAD

**Issue by RayBB** [casimir/frigoligo#303]
Happening on the latest 2.1.0
A small followup to https://github.com/casimir/frigoligo/issues/289

Video demo:

https://github.com/user-attachments/assets/8b635f51-3d99-488b-b0f1-5bf5e1e14abd

**Comment by casimir** [comment]
The bug was still happening on some specific circumstances. It should be definitly fixed by https://github.com/casimir/frigoligo/commit/f8244e14941249af3a6c49bfa1bd746c8f81443e.

**Comment by casimir** [comment]
The update with these fixes has been deployed.
