### ISSUE TITLE
Can't communicate to server in http

### ISSUE THREAD

**Issue by casimir** [casimir/frigoligo#304]
The protocol (`https`) is hardcoded in the code. It makes the use case of a server in the local network like `http://192.168.4.55:7000` impossible to work.

Follow up of #201.

**Comment by Froggy232** [comment]
Hi,
I have this exact problem where Wallabag is accessible only through a wireguard private network, so no need for https.
Is there any hope for http support?
I would love to use your apps, but it's the only thing that restrain it. I can make a small donation in cryptocurrencies if it can help!
Also, thanks for your soft, it's nice to have an android native app for wallabag.
Thanks you!

**Comment by casimir** [comment]
Just been released with v2.2.0.
