### ISSUE TITLE
Version 2.1.3 presents itself as 2.1.2

### ISSUE THREAD

**Issue by noodlejetski** [casimir/frigoligo#306]
I've installed the latest version (2.1.3) of the arm64-v8a apk from Github releases on my two Android devices (Fairphone 4 running an Android 14-based custom ROM and Samsung Galaxy Tab S7 on Android 13). the App info window in the device 
settings displays version 2.1.2, while Frigoligo's Version section shows 2.1.2+2037.

**Comment by gabrielparca** [comment]
having same issue on my Samsung A34 (SM-A346E)

![Screenshot_20241227_161927_Brave - Beta.png](https://github.com/user-attachments/assets/dfb27686-8c2b-40e8-93d9-90c835675a36)

![Screenshot_20241227_161854_App Manager.png](https://github.com/user-attachments/assets/5d396879-e248-46fd-a9c2-48266716736c)

**Comment by casimir** [comment]
Thanks for the report, it is an oversight during the last release cut. Manual operations...

It's not a big deal since 2.1.2 and 2.1.3 are virtually the same, the only difference is a change to some packaging metadata for another platform.

I have added a disclaimer in the release description for good measure.

**Comment by noodlejetski** [comment]
yeah I know it's not a big deal, I only noticed it because I update the app via Obtainium, and it keeps saying there's a new version of the app available because of that.

**Comment by casimir** [comment]
I didn't know about Obtainium, looks like a nice tool. Cutting a release is not super easy and the next one (2.2.0) is coming soon so I would leave it as it is. In the meantime, tell me if it's too annoying and I will think about something.

**Comment by noodlejetski** [comment]
no no, no worries, I just pointed out the circumstances of how I found that. you keep doing you :)
