### ISSUE TITLE
impossible to install on my Android phone

### ISSUE THREAD

**Issue by axac** [casimir/frigoligo#54]
I am under Adroid 11, it is not possible for me to install this version (04.0) it just marked (application not installed) The 0.3.2 installation works.

**Comment by casimir** [comment]
From what I could find It can be caused by a lot of different things... I finally managed to launch the open testing campaign on the Playstore. I could work better https://play.google.com/store/apps/details?id=net.casimirlab.frigoligo.

**Comment by axac** [comment]
Fine !
Thanks !

**Comment by casimir** [comment]
Just so you know, the underlying issue should have been fixed with the latest release: https://github.com/casimir/frigoligo/issues/56#issuecomment-1677380376.
